SELECT * FROM SALES;

----- EXTRACTING MONTH AND YEAR------
CREATE VIEW  NEW_SALES AS
SELECT *,
YEAR (InvoiceDATE) AS YEARS,
MONTH (INVOICEDATE)AS MONTHS
FROM SALES;

------- CALCULATING REVEUNE ------------
SELECT *, (Quantity* Price) AS REVENUE FROM NEW_SALES;



 -----NEGATIVE PRICE-----
 SELECT COUNT(*) NEGATIVE_COUNT FROM SALES
 WHERE Quantity<0;

----- CONVERTING NEAGTIVE QUANTITY TO POSITIVE-----
CREATE VIEW NEW_VIEW AS
SELECT *, 
CASE 
WHEN Quantity<0 THEN Quantity*(-1)
ELSE Quantity 
END AS Quantities
FROM NEW_SALES;
 
SELECT  * FROM NEW_VIEW;
------- TOTAL REVEUNE BY MONTH------
 SELECT MONTHS,ROUND(SUM(REVENUE),2) TOTAL_REVENUE
 FROM (SELECT *, (Quantities* Price) AS REVENUE FROM NEW_VIEW) AS S
 GROUP BY MONTHS
 ORDER BY 1;

 --------- TOTAL REVEUNE BY YEAR-------
 SELECT YEARS,ROUND(SUM(REVENUE),2) TOTAL_REVENUE
 FROM (SELECT *, (Quantities* Price) AS REVENUE FROM NEW_VIEW) AS S
 GROUP BY YEARS
 ORDER BY 1;

 ----- TOP 3 MONTH IN REVEUNE -----
 SELECT TOP 3 YEARS, MONTHS,ROUND(SUM(REVENUE),3) TOTAL_REVENUE
 FROM (SELECT *, (Quantities* Price) AS REVENUE FROM NEW_VIEW) AS S
 GROUP BY YEARS, MONTHS
 ORDER BY 3 DESC;


 ------- MOST CONTRIBUTING CUSTOMER----
 SELECT  TOP 10 Customer_ID, ROUND(SUM(REVENUE),2) AS REVENUE 
 FROM   (SELECT *, (Quantities* Price) AS REVENUE FROM NEW_VIEW) AS S
 GROUP BY Customer_ID
 HAVING Customer_ID IS NOT NULL
 ORDER BY 2 DESC;


 ------TOP 5 COUNTRY REVENUE------
 SELECT TOP 5 Country,SUM(REVENUE) TOTAL_REVENUE
 FROM (SELECT *, (Quantities* Price) AS REVENUE FROM NEW_VIEW) AS S
 GROUP BY Country
 ORDER BY 2 DESC;

 -------- COUNTRY WITH HIGHEST SOLD QUANTITY---------
 SELECT TOP 10 Country,SUM(Quantities) TOTAL_QUANTITY
 FROM NEW_VIEW
 GROUP BY Country
 ORDER BY 2 DESC;

 ------ HIGHEST SOLD STOCK  WITH PRICE -----
 SELECT TOP 10 StockCode,
 ROUND(SUM(Quantities),2) TOTAL_QUANTITY,
 ROUND(SUM(Price),2) TOTAL_PRICE
 FROM NEW_VIEW
 GROUP BY StockCode
 ORDER BY 2 DESC,3 DESC;


 ----- DAYS_OF WEEK ---
 SELECT *,
 DATENAME(WEEKDAY,InvoiceDATE) AS WEEK_DAY
 FROM NEW_VIEW;

 ----- MOST SALES ON WHICH DAY----
 SELECT WEEK_DAY,ROUND(SUM(Quantities),3) TOTAL_SALE
 FROM (SELECT *, 
		DATENAME(WEEKDAY,InvoiceDATE) AS WEEK_DAY
		FROM NEW_VIEW) AS S
 GROUP BY WEEK_DAY
 ORDER BY 2 DESC;
 


 ------ SHIFT WISE SALES------

 WITH HOURLY_SALE AS(
	 SELECT *, 
		CASE 
		  WHEN DATEPART(HOUR,INVOICEDATE)>12 THEN 'MORNING'
		  WHEN DATEPART(HOUR,INVOICEDATE) BETWEEN 12 AND 17 THEN 'AFTERNOON'
		  ELSE 'EVENING'
		  END AS SHIFTS
	FROM NEW_VIEW)
SELECT 
SHIFTS,
SUM(Quantities) AS TOTAL_SALE
FROM HOURLY_SALE
GROUP BY SHIFTS
ORDER BY 2 DESC;


----- ORDER VOLUME AS MONTH  AND YEAR-------
SELECT YEARS, MONTHS, COUNT(DISTINCT Invoice) AS Order_Volume
FROM NEW_VIEW
GROUP BY YEARS, MONTHS
ORDER BY YEARS, MONTHS;
